### ISSUE TITLE
Did you plan to add a new tab resque-web ?

### ISSUE THREAD

**Issue by nfo** [eclubb/resque-approval#1]
Hi,
Did you already start working on this ? I could do it if I decide to use this plugin.
Also, did you plan a notification system, when a job needs an approval ?

**Comment by eclubb** [comment]
I don't have any plans at the moment to work on a resque-web tab, though I would be happy to consider any contributions.

What sort of notifications do you have in mind?  Currently, I just poll for pending jobs using `Resque::Plugins::Approval.pending_job_keys`
